name: refferal_code
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  flutter_sms_autofill: ^1.0.4
  pin_code_fields: ^7.4.0
  sms_autodetect: ^1.0.8
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

